# Practica 05: Analisis de Datos Exploratorio con Python y Jupiter Notebook

*Programa de Estudios:* Ingeniería en Desarrollo y Gestón de Software \
*Asignatura:* Extracción de Conocimiento en Bases de Datos \
*Docente:* M.T.I Marco A. Ramírez Hernández \
*Periodo:* Mayo - Agosto 23026

### Unidad 2: Preparación de los Datos

**Nombre del Estudiante:** Karen Lizbeth Negrete Hernández\
**Matricula:** 230570\
**Grado y Grupo:** 9 B IDGS

El estudiante practicará como realizar un analasis exploratorio de datos (EDA), utilizando el lenguaje de
programación de Python, y librerias comunes para la carga, manipulación, análisis y visualización prevla de un
conjunto de datos (Dataset), para esta práctica se utilizarán las librerlas de:
    
-Pandas
-Numpy
-Seaborn
-Matplotlib

1. Importar las librerias necesarlas para realizar el EDA
Comenzamos por importar la libreria que nos permitirá manipula los datos del dataset extraidos de una fuente de
datos (datasource)

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Creamos un DataFrame, leyendo el archivo delimitado por comas (.CSV)

In [26]:
pokemons=pd.read_csv('./Pokemon.csv')

In [14]:
pokemonss=pd.read_csv('./Pokemon_Evolution_Stages.csv')

3. Imprimimos el resultado de la lectura
Este comando imprime en una tabla las columnas y las filas del dataframe, siempre de manera estándar nos mostrara
los primeros 5 y los últimos 5 registros del dataframe.

In [16]:
pokemons

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
801,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
802,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
803,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
804,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Ejercicio de Traer 50 registros

In [7]:
pokemons.head(50)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
5,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
6,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
7,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
8,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
9,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
10,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
11,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
12,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
13,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
14,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
15,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
16,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
17,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
18,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
19,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False
20,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
21,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
22,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
23,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
24,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
25,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
26,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False
27,21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False
28,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False
29,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
30,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False
31,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
32,26,Raichu,Electric,NaN,485,60,90,55,90,80,110,1,False
33,27,Sandshrew,Ground,NaN,300,50,75,85,20,30,40,1,False
34,28,Sandslash,Ground,NaN,450,75,100,110,45,55,65,1,False
35,29,Nidoran♀,Poison,NaN,275,55,47,52,40,40,41,1,False
36,30,Nidorina,Poison,NaN,365,70,62,67,55,55,56,1,False
37,31,Nidoqueen,Poison,Ground,505,90,92,87,75,85,76,1,False
38,32,Nidoran♂,Poison,NaN,273,46,57,40,40,40,50,1,False
39,33,Nidorino,Poison,NaN,365,61,72,57,55,55,65,1,False
40,34,Nidoking,Poison,Ground,505,81,102,77,85,75,85,1,False
41,35,Clefairy,Fairy,NaN,323,70,45,48,60,65,35,1,False
42,36,Clefable,Fairy,NaN,483,95,70,73,95,90,60,1,False
43,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
44,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
45,39,Jigglypuff,Normal,Fairy,270,115,45,20,45,25,20,1,False
46,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,False
47,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
48,42,Golbat,Poison,Flying,455,75,80,70,65,75,90,1,False
49,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False

4. Obtener una muestra aleatoria de registros del dateframe usuando el método .sample

Como parámetro de entrada podemos definir un entorno que determina el tamaño de la muestra

In [9]:
pokemons.sample(7) ## Obtiene una muestra de 7 pokemones aleatorio

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
312,286,Breloom,Grass,Fighting,460,60,130,80,60,60,70,3,False
68,61,Poliwhirl,Water,NaN,385,65,65,65,50,50,90,1,False
56,50,Diglett,Ground,NaN,265,10,55,25,35,45,95,1,False
426,383,Groudon,Ground,NaN,670,100,150,140,100,90,90,3,True
696,630,Mandibuzz,Dark,Flying,510,110,65,105,55,95,80,5,False
500,447,Riolu,Fighting,NaN,285,40,70,40,35,40,60,4,False
594,530,Excadrill,Ground,Steel,508,110,135,60,50,65,88,5,False

5.- Obtener una muestra de rangos definidos usando .iloc

In [8]:
pokemons_100_to_200 = pokemons.iloc[100:200]
pokemons_100_to_200

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
100,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
101,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False
102,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
103,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
104,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,179,Mareep,Electric,NaN,280,55,40,40,65,45,35,2,False
196,180,Flaaffy,Electric,NaN,365,70,55,55,80,60,45,2,False
197,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
198,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
199,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False

6.- Como saber las columnas o atributos tiene el datafame

In [10]:
pokemons.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

| Campo | Descripción |
|--------|-------------|
| **#** | El ID o número de identificación del Pokémon. |
| **Name:** | El nombre del Pokémon. |
| **Type 1:** | Se refiere a las propiedades elementales (tipos) asociadas tanto al Pokémon como a sus movimientos. |
| **Type 2:** | Los Pokémon pueden tener hasta dos tipos (Pokémon de tipo dual); los movimientos solo pueden tener uno. |
| **Total:** | Representa la suma de todos los stats, lo que da una idea de qué tan fuerte es el Pokémon. |
| **HP:** | (Puntos de Salud) Es qué tanto aguante tiene un Pokémon antes de que lo dejen fuera de combate (se desmaye). |
| **Attack:** | La fuerza de los ataques físicos del Pokémon. |
| **Defense:** | Qué tanto aguanta el Pokémon contra los ataques físicos del rival. |
| **Evolution_Level:** | Nivel de evolución del Pokémon. |
| **Sp. Atk:** | Ataque Especial: el poder de los movimientos especiales del Pokémon. |
| **Sp. Def:** | Defensa Especial: qué tan resistente es el Pokémon ante los ataques especiales. |
| **Speed:** | Velocidad del Pokémon; el que tenga más velocidad es el que ataca primero. |
| **Generation:** | Se refiere a la generación de la serie de juegos a la que pertenece. |
| **Legendary:** | Indica si el Pokémon es legendario o no (son muy raros y poderosos). Es un valor booleano (sí/no). |

7. Explorar la composición y ausencia de datos (METADATA) CON .info

La libreria de pandas, incluye un método que nos permite evaluar el tipo de datos y su composicion y ausencia

In [27]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805 entries, 0 to 804
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           805 non-null    int64
 1   Name        805 non-null    object
 2   Type 1      805 non-null    object
 3   Type 2      416 non-null    object
 4   Total       805 non-null    int64
 5   HP          805 non-null    int64
 6   Attack      805 non-null    int64
 7   Defense     805 non-null    int64
 8   Sp. Atk     805 non-null    int64
 9   Sp. Def     805 non-null    int64
 10  Speed       805 non-null    int64
 11  Generation  805 non-null    int64
 12  Legendary   805 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 76.4+ KB